### ISSUE TITLE
External Linkage sends shifted pos/rot when 'Room' configuration edited in base game.

### ISSUE THREAD

**Issue by kan8pachi** [Snow1226/CameraPlus#26] opened 2023-08-16 16:09 UTC
The camera position and rotation sent from `External Linkage (VMC Protocol)` does not seem to be as intended when `Room` configuration is edited in game setting.
ゲーム内の `Room` 設定が変更されていると、`External Linkage (VMC Protocol)` から送られるカメラの位置と向きがその分ずれるようです。

How to reproduce:
- `Add New Camera` in CameraPlus setting in the game window, and set `External linkage` to it as `Sender` with proper Address and Port.
  CameraPlusのカメラに、 `External linkage`を適当に設定します。
- Configure receiver like `VirtualMotionCapture` to receive it.
  ばもきゃ等で受信します。
- Move the camera (of `CameraPlus`) with `External Linkage` in front of my avatar in the any scene. (just for making it easy to understand)
  CameraPlusのカメラを、自分の正面に持ってきます。
- If room setting in base game is default (Rotation: 0, X Offset: 0.00, Y Offset: 0.00, Z Offset: 0.00) then the `CameraPlus` camera and the `VirtualMotionCapture` camera has the same position and rotation. Maybe this is a natural behaviour.
  ゲーム内の `Room` 設定が変更されていない場合は、特に不自然な挙動はありません。
- If room setting in base game is changed (like Rotation: 90, ...) then the `VirtualMotionCapture` camera shoots from my right? side even though the `CameraPlus` camera is still in front of my body in VR. Those two cameras have different FOV as a result, which I think is an unnatural behaviour.
  ゲーム内の `Room` 設定が変更されている場合、例えば90度回すと、CameraPlusのカメラはVR空間では変わらず正面から撮る位置にあるにもかかわらず、ばもきゃのカメラは右側？から撮影する角度になり、不自然に見えます。

**Comment by Snow1226** [comment] 2023-08-19 09:24
ありがとうございます、確かにExternalSender時にRoomAdjustを考慮していません。
1.31においてはNoodleも更新された影響で変更を入れるため、PR#27については検討させてください。

Thanks, certainly not considering RoomAdjust when ExternalSender.
In 1.31, Noodle will also be updated and changes will be made, so please consider PR#27.

**Comment by kan8pachi** [comment] 2023-08-19 15:28
Thank you so much. PR #27 is just for sharing the workaround that is working at maigo-san's environment regarding RoomAdjust only, so no problem. Please just close it when you no longer need it.
Since our use case doesn't currently depend on Noodle so much and the workaround above is almost good for us, please take your time fixing it including Noodle!

**Comment by Snow1226** [comment] 2023-08-20 07:30
I tried reconfirming the code and behavior, but since the changes in the Room settings are absorbed elsewhere,
For VMCProtocol, there should be no problem in sending ThirdPersonPos and ThirdPersonRot as they are.
I checked in 3 environments, but I can't confirm Maigo's symptoms.

**Comment by Snow1226** [comment] 2023-08-20 07:32
Additional information may be required for verification.

**Comment by Snow1226** [comment] 2023-08-20 07:50
CameraPlus is now
CameraPlusBehaviour
- Camera Plus Origin　
- - inGame Camera
It has a hierarchy structure of , and the inGame Camera Local value is sent to the VMC.
RoomAdjust is a structure that doesn't need to consider the rotation of in-game objects, but since only Noodle's PlayerTrack is affected, only GameScene handles RoomAdjust in Origin.
Therefore, LocalPosition and LocalRotation of inGame Camera are not affected by RoomAdjust at all.
And it sends Position and Euler as it looks to VMC.

Development environment (1.31.0)
My delivery environment (1.29.1)
I built (1.29.1) on a new PC and entered Maigo's Room settings and more extreme values, but I couldn't confirm the reproduction.

**Comment by Snow1226** [comment] 2023-08-21 16:09
I'm sorry, I was able to reproduce the situation.
There is no problem with the code you provided, so I will merge it.
Thank you for the issue.

**Closed as completed by Snow1226** 2023-08-21 16:09 UTC
